/* STORED PROCEDURE CREATION CHECK */

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'usp_TestQuestion_EstimateTotal')
DROP PROCEDURE [dbo].usp_TestQuestion_EstimateTotal 
GO